services:
  seahorse:
    build: .
    image: seahorse
    container_name: seahorse
    restart: unless-stopped
    ports:
      - 9843:9843 # http
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./compose-templates:/compose-templates:ro
      - ./config.yml:/config.yml
      - ./environment:/environment:ro
